force-app/main/default/objects/Lease__c/Lease__c.object-meta.xml
<CustomObject>
    <label>Lease</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lease Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Leases</relationshipLabel>
    <relationshipName>Leases</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lease__c/fields/Rent_Price__c.field-meta.xml
<CustomField>
    <fullName>Rent_Price__c</fullName>
    <label>Rent Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease__c/fields/Resident__c.field-meta.xml
<CustomField>
    <fullName>Resident__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resident</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leases</relationshipLabel>
    <relationshipName>Leases</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Property ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Resident__c.field-meta.xml
<CustomField>
    <fullName>Resident__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resident</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resident_Invoice__c/Resident_Invoice__c.object-meta.xml
<CustomObject>
    <label>Resident Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Resident Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resident Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resident_Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Resident_Invoice__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rent Payment</fullName>
            </value>
            <value>
                <fullName>Service Appointment Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resident_Invoice__c/fields/Resident__c.field-meta.xml
<CustomField>
    <fullName>Resident__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resident</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Resident Invoices</relationshipLabel>
    <relationshipName>Resident_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Invoice_Schedulable.cls
global class Invoice_Schedulable Implements Schedulable {
    global void execute(SchedulableContext sc) {
        createInvoice();
    }
    
    public void createInvoice(){
        List<Resident_Invoice__c> invoices = new List<Resident_Invoice__c>();
        List<Lease__c> listLeases = [SELECT ID, Resident__c, Property__c, Property__r.Name, Rent_Price__c, Start_Date__c, End_Date__c 
                       FROM Lease__c 
                       WHERE Start_Date__c <= TODAY 
                       AND End_Date__c >= TODAY];

        Date dToday = Date.today();
        String dateStr = dToday.year() + '/' + dToday.month() + '/' + dToday.day();


        for(Lease__c l: listLeases){
            Resident_Invoice__c rentInvoice = new Resident_Invoice__c(Invoice_Date__c=dToday,
                                                                 Resident__c=l.Resident__c,
                                                                 Total__c=l.Rent_Price__c,
                                                                 Reason__c='Rent payment',
                                                                 Subject__c='Rent payment '  + l.Property__r.Name + ' ' + dateStr);
            invoices.add(rentInvoice);
        }
        Database.insert(invoices, false);
    }
}