force-app/main/default/objects/Resident_Invoice__c/Resident_Invoice__c.object-meta.xml
<CustomObject>
    <label>Resident Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Resident Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resident Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resident_Invoice__c/fields/Invoice_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Due_Date__c</fullName>
    <formula>Invoice_Date__c + 10</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Resident_Invoice__c/fields/Resident__c.field-meta.xml
<CustomField>
    <fullName>Resident__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resident</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Resident Invoices</relationshipLabel>
    <relationshipName>Resident_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ExtensionInvoiceController.cls
public class ExtensionInvoiceController {
    
    private final Resident_Invoice__c resInvoice;
    public Case invoiceCase {get; set;}
    public Contact invoiceContact {get; set;}
    public Account invoiceAccount {get; set;}
     
     
    public ExtensionInvoiceController
		(ApexPages.StandardController stdController) {
            stdController.addFields(new List<String>{'Id', 'Name', 'Subject__c', 'Resident__c', 'Invoice_Due_Date__c'});
        	this.resInvoice =(Resident_Invoice__c)stdController.getRecord();
            
            invoiceContact = [SELECT Id, Name, Phone, Email, AccountId FROM Contact WHERE Id = :resInvoice.Resident__c][0];
            invoiceAccount = [SELECT Id, Name, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry 
                              FROM Account WHERE Id =: invoiceContact.AccountId];

                           
    }

    public void saveNew(){        
        String invName = resInvoice.Name;
        String fileName = 'Invoice_' + invName + '.pdf';
        Apexpages.currentPage().getHeaders().put('content-disposition', 'attachment; filename=' + fileName);   
    }
    
}